### ISSUE TITLE
Latest version not published to NPM

### ISSUE THREAD

**Issue by ShaunParsons** [eBay/ebay-oauth-nodejs-client#9] opened 2020-12-21 15:43 UTC
Trying to use this library and I'm getting some strange behaviour when passing `options` into `generateUserAuthorizationUrl`, only to find the changes in https://github.com/eBay/ebay-oauth-nodejs-client/pull/8 are not currently released. Could the latest master branch be released?

**Comment by pajaydev** [comment] 2020-12-23 23:09
@ShaunParsons  Thanks for creating this issue. I have released the changes with newer version, kindly verify

```
npm install ebay-oauth-nodejs-client@1.2.1
```

**Comment by pajaydev** [comment] 2020-12-23 23:10
Closing this issue, kindly create a new one of the issue is not resolved.

**Closed by pajaydev** 2020-12-23 23:10 UTC
